name: tts_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  flutter_tts: ^4.2.1
  http: ^1.3.0
  audioplayers: ^6.1.0
  flutter_dotenv: ^5.2.1
  equatable: ^2.0.7
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: any

flutter:
  uses-material-design: true

